name: Al Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run tests
      env:
        # Mock API keys for testing
        SHIPSTATION_API_KEY: test_key:test_secret
        NOTION_API_KEY: test_notion_key
        ANTHROPIC_API_KEY: test_anthropic_key
      run: |
        pytest tests/ -v --cov=al --cov-report=term-missing --cov-fail-under=80

    - name: Run regression tests (must pass)
      env:
        SHIPSTATION_API_KEY: test_key:test_secret
        NOTION_API_KEY: test_notion_key
        ANTHROPIC_API_KEY: test_anthropic_key
      run: |
        pytest tests/regression/ -v --tb=short
        if [ $? -ne 0 ]; then
          echo "❌ REGRESSION TESTS FAILED - Known bugs have returned!"
          exit 1
        fi

    - name: Check code coverage
      run: |
        pytest --cov=al --cov-report=term --cov-fail-under=80
